### ISSUE TITLE
Error opening single issue comics

### ISSUE THREAD

**Issue by Hoplake** [hmhrex/Tenma#26]
Collections / Volumes open just fine, but when trying to open a single comics end in error. It seems they are opened from the wrong path.

Error message is: 'files/files/Kato (2010)/Issue 6.cbz', files is twice in the path.

**Comment by hmhrex** [comment]
This seems to happen when it's in a subfolder (i.e. `files/series/comic`). I'll take a look and see what's going on.

**Comment by hmhrex** [comment]
I'm actually having trouble recreating this one.
* What operating system are you on?
* What is the correct file path of the issue?

**Comment by hmhrex** [comment]
I was able to recreate this problem finally and got it fixed!
