### ISSUE TITLE
Files with same name don't get added to Tenma

### ISSUE THREAD

**Issue by Hoplake** [hmhrex/Tenma#27]
I took your wiki instructions about naming the files took literally :D I named my files like this:
Cryptozoic Man (2013)
* Issue 1.cbz
* Issue 2.cbz
* Issue 3.cbz
* Issue 4.cbz
Doctor Who (2008)
* Issue 1.cbz
* Issue 2.cbz
* Issue 3.cbz
* Issue 4.cbz
* Issue 5.cbz
* Issue 6.cbz
Doctor Who (2011)
* Issue 13.cbz
* Issue 14.cbz
* Issue 15.cbz
* Issue 16.cbz
Dungeons & Dragons - The Legend of Drizzt - Neverwinter Tales - Volume 1.cbz
Escape from New York (2014) - Volume 1.cbz
Escape from New York (2014) - Volume 2.cbz
Kato (2010)
* Issue 1.cbz
* Issue 10.cbz
* Issue 11.cbz
* Issue 12.cbz
* Issue 13.cbz
* Issue 14.cbz
* Issue 2.cbz
* Issue 3.cbz
* Issue 4.cbz
* Issue 5.cbz
* Issue 6.cbz
* Issue 7.cbz
* Issue 8.cbz
* Issue 9.cbz
This resulted in situation where, Doctor Who (2011) and Cryptozoic Man where imported, but from Kato only issues 5-12 (as files named issue 1-4 where already imported by crypto and issues 13-14 where imported by Who) and none of the Doctor Who (2008) got imported as the issue names where all already imported.

**Comment by hmhrex** [comment]
I updated the documentation so that it clearly states to not explicitly rename your comic files to `Issue #` like we talked about, however, this is still a bug.

**Comment by hmhrex** [comment]
When a file is processed, it's name gets stored in a file in the `files` directory called `.processed-files`. This makes it easy to determine which files have already been processed. 

Right now, it stores only the file name. I'll fix this to store the whole path to differentiate the different files with the same name.
