### ISSUE TITLE
Import function overwrites custom processed volumes

### ISSUE THREAD

**Issue by Hoplake** [hmhrex/Tenma#28]
If I set comicvine id to volume and click "reprocess", Tenma fetches a name and a cover for the comic (+all the other information).

If I then hit the "Import Comics" button to add new comics, this will over write the custom fetched volume name and cover image, although it does preserve the comicvine id. So I will have to go and hit "reprocess" again on the volumes.

I'll add photos of before and after "import comics"

![beforeimport](https://user-images.githubusercontent.com/16816103/27624710-91285b7a-5bea-11e7-883d-e2fb5a26d68b.PNG)
![afterimport](https://user-images.githubusercontent.com/16816103/27624711-91284054-5bea-11e7-9df6-f668229dcb6e.PNG)

**Comment by hmhrex** [comment]
This is actually related to issue #27. Closing in favor of that.
